In [1]:
import tensorflow as tf
import numpy as np

#Допоміжна функція для друку інформації про тензор
def print_tensor_info(name, tensor):
    """Виводить ім'я тензора та його основні властивості."""
    print(f"\nТензор {name}:")
    print(tensor.numpy()) # Використовуємо .numpy() для чистого виводу значень
    print("dtype:", tensor.dtype.name) # Використовуємо .name для чистого імені типу
    print("shape:", tensor.shape)
    # tf.rank(tensor).numpy() може бути повільним, але є правильним способом
    print("rank:", tf.rank(tensor).numpy())


#2. Ініціалізація та демонстрація

# tf.constant: Створення з фіксованими даними
tensor_const = tf.constant([[1, 2, 3], [4, 5, 6]])
print_tensor_info("tf.constant (Фіксовані дані)", tensor_const)

# tf.zeros: Створення з нулями
tensor_zeros = tf.zeros([2, 3])
print_tensor_info("tf.zeros (Заповнений нулями)", tensor_zeros)

# tf.ones: Створення з одиницями
tensor_ones = tf.ones([3, 2])
print_tensor_info("tf.ones (Заповнений одиницями)", tensor_ones)

# tf.random.uniform: Створення зі випадковими значеннями
tensor_random = tf.random.uniform([2, 2], minval=0, maxval=10, dtype=tf.float32)
print_tensor_info("tf.random.uniform (Випадкові значення)", tensor_random)


Тензор tf.constant (Фіксовані дані):
[[1 2 3]
 [4 5 6]]
dtype: int32
shape: (2, 3)
rank: 2

Тензор tf.zeros (Заповнений нулями):
[[0. 0. 0.]
 [0. 0. 0.]]
dtype: float32
shape: (2, 3)
rank: 2

Тензор tf.ones (Заповнений одиницями):
[[1. 1.]
 [1. 1.]
 [1. 1.]]
dtype: float32
shape: (3, 2)
rank: 2

Тензор tf.random.uniform (Випадкові значення):
[[8.589178  6.6711817]
 [0.5696547 9.1973   ]]
dtype: float32
shape: (2, 2)
rank: 2


In [3]:
import tensorflow as tf
import numpy as np

# Допоміжна функція для друку інформації про тензор
def print_tensor_info(name, tensor):
    """Виводить ім'я тензора, його вміст та форму."""
    # print(f"\nТензор {name} ({tensor.dtype.name}):") # можна додати dtype
    print(f"\nТензор {name}:")
    print(tensor.numpy())
    print("shape:", tensor.shape)

# Ініціалізація початкового тензора
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print_tensor_info("Початковий (int32)", tensor)
print("--------------------------------------------------")

# 1. Зміна Типу Даних: int32 -> float32
tensor_float = tf.cast(tensor, tf.float32)
print_tensor_info("tf.cast (-> float32)", tensor_float)

# 2. Зміна Форми: 2x3 -> 3x2
tensor_reshaped = tf.reshape(tensor, [3, 2])
print_tensor_info("tf.reshape (-> 3x2)", tensor_reshaped)

# 3. Розширення Розмірності: (2, 3) -> (1, 2, 3)
tensor_expanded = tf.expand_dims(tensor, axis=0)
print_tensor_info("tf.expand_dims (axis=0)", tensor_expanded)

# 4. Стискання Розмірності: (1, 2, 3) -> (2, 3)
tensor_squeezed = tf.squeeze(tensor_expanded)
print_tensor_info("tf.squeeze (видалення розмірності 1)", tensor_squeezed)


Тензор Початковий (int32):
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
--------------------------------------------------

Тензор tf.cast (-> float32):
[[1. 2. 3.]
 [4. 5. 6.]]
shape: (2, 3)

Тензор tf.reshape (-> 3x2):
[[1 2]
 [3 4]
 [5 6]]
shape: (3, 2)

Тензор tf.expand_dims (axis=0):
[[[1 2 3]
  [4 5 6]]]
shape: (1, 2, 3)

Тензор tf.squeeze (видалення розмірності 1):
[[1 2 3]
 [4 5 6]]
shape: (2, 3)


In [4]:
import tensorflow as tf
import ast
import sys

#1. Словник для операцій
OPERATIONS_MAP = {
    '1': (tf.add, '+'),
    '2': (tf.subtract, '-'),
    '3': (tf.multiply, '*'),
    '4': (tf.divide, '/')
}

# Безпечне перетворення рядка на тензор
def safe_parse_tensor(input_str: str, name: str) -> tf.Tensor:
    try:
        # Використовуємо ast.literal_eval для безпечного парсингу
        list_data = ast.literal_eval(input_str)

        # Якщо користувач ввів просто число, обертаємо його у список
        if not isinstance(list_data, (list, tuple)):
            list_data = [list_data]

        return tf.constant(list_data, dtype=tf.float32)
    except (ValueError, SyntaxError, TypeError):
        # Обробка помилок парсингу
        print(f"\n[ПОМИЛКА]: Неправильний формат для {name}. Переконайтеся, що це коректний список або число.")
        # Зупиняємо виконання, оскільки без тензорів далі працювати не можна
        sys.exit(1)


print("Простий калькулятор TensorFlow!")
print("Введіть два тензори у вигляді списків, наприклад: [1, 2, 3] або [[1, 2], [3, 4]]")

# Введення та парсинг
a_str = input("Введіть перший тензор: ")
b_str = input("Введіть другий тензор: ")

tensor_a = safe_parse_tensor(a_str, "першого тензора")
tensor_b = safe_parse_tensor(b_str, "другого тензора")


# Вибір операції
print("\nОберіть операцію:")
for key, (_, symbol) in OPERATIONS_MAP.items():
    print(f"{key} - {symbol}")

operation_choice = input("Введіть номер операції: ")


# Виконання обраної операції
if operation_choice in OPERATIONS_MAP:
    op_func, op_symbol = OPERATIONS_MAP[operation_choice]

    try:
        result = op_func(tensor_a, tensor_b)

        # Результат
        print(f"\nОперація: {op_symbol}")
        print("-" * 20)
        print(f"Тензор А ({tensor_a.shape}):\n{tensor_a.numpy()}")
        print(f"Тензор B ({tensor_b.shape}):\n{tensor_b.numpy()}")
        print("-" * 20)
        print(f"Результат ({result.shape}):\n{result.numpy()}")

    except tf.errors.InvalidArgumentError as e:
        print(f"\n[ПОМИЛКА TENSORFLOW]: Операція '{op_symbol}' неможлива через несумісні форми тензорів (Broadcasting error).")
        print(f"Форма A: {tensor_a.shape}, Форма B: {tensor_b.shape}")

else:
    print("\nНеправильний вибір операції!")

Простий калькулятор TensorFlow!
Введіть два тензори у вигляді списків, наприклад: [1, 2, 3] або [[1, 2], [3, 4]]
Введіть перший тензор: 3
Введіть другий тензор: 2

Оберіть операцію:
1 - +
2 - -
3 - *
4 - /
Введіть номер операції: 1

Операція: +
--------------------
Тензор А ((1,)):
[3.]
Тензор B ((1,)):
[2.]
--------------------
Результат ((1,)):
[5.]


In [ ]:
import tensorflow as tf

# Задаємо матрицю (варіант 5)
matrix = [
    [4, 2, 8, 5, 9, 5],
    [1, 1, 3, 7, 10, 2],
    [1, 7, 2, 1, 8, 7],
    [5, 4, 5, 7, 6, 6],
    [8, 6, 6, 7, 10, 9],
    [7, 9, 5, 7, 4, 5]
]

# Створюємо тензор на основі матриці
tensor = tf.constant(matrix, dtype=tf.int32)

# Вивід початкового тензора
print("Початковий тензор:")
print(tensor)

# Транспонування тензора
tensor_transposed = tf.transpose(tensor)

# Вивід транспонованого тензора
print("\nТранспонований тензор:")
print(tensor_transposed)

Початковий тензор:
tf.Tensor(
[[ 4  2  8  5  9  5]
 [ 1  1  3  7 10  2]
 [ 1  7  2  1  8  7]
 [ 5  4  5  7  6  6]
 [ 8  6  6  7 10  9]
 [ 7  9  5  7  4  5]], shape=(6, 6), dtype=int32)

Транспонований тензор:
tf.Tensor(
[[ 4  1  1  5  8  7]
 [ 2  1  7  4  6  9]
 [ 8  3  2  5  6  5]
 [ 5  7  1  7  7  7]
 [ 9 10  8  6 10  4]
 [ 5  2  7  6  9  5]], shape=(6, 6), dtype=int32)


In [ ]:
import tensorflow as tf

# Задаємо матриці
matrix1 = [
    [9, 5, 9, 9],
    [6, 2, 7, 3],
    [6, 2, 8, 7],
    [10, 8, 3, 4]
]

matrix2 = [
    [9, 3, 4, 9],
    [5, 5, 7, 8],
    [4, 1, 4, 10],
    [1, 6, 6, 6]
]

# Створюємо тензори
A = tf.constant(matrix1, dtype=tf.int32)
B = tf.constant(matrix2, dtype=tf.int32)

# Множення зліва (A * B)
left_mul = tf.matmul(A, B)
print("Множення зліва (A * B):")
print(left_mul)

# Множення справа (B * A)
right_mul = tf.matmul(B, A)
print("\nМноження справа (B * A):")
print(right_mul)

Множення зліва (A * B):
tf.Tensor(
[[151 115 161 265]
 [ 95  53  84 158]
 [103  78 112 192]
 [146  97 132 208]], shape=(4, 4), dtype=int32)

Множення справа (B * A):
tf.Tensor(
[[213 131 161 154]
 [197 113 160 141]
 [166 110 105 107]
 [141  77 117  93]], shape=(4, 4), dtype=int32)


In [ ]:
import tensorflow as tf

# Матриця коефіцієнтів
A = tf.constant([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
], dtype=tf.float32)

# Вектор правих частин
b = tf.constant([8, -11, -3], dtype=tf.float32)

# Розв'язок системи
x = tf.linalg.solve(A, tf.reshape(b, (-1, 1)))

# Округлення до 3 знаків після коми
x_rounded = tf.round(x * 1000) / 1000

print("Розв'язок системи рівнянь:")
print(x_rounded.numpy())

Розв'язок системи рівнянь:
[[ 2.]
 [ 3.]
 [-1.]]
